### ISSUE TITLE
Issue with downloading the folder

### ISSUE THREAD

**Issue by dam2452** [H4wk507/cda-downloader#2]
When I try to download a folder, of which I have already downloaded a significant part, just checking what I've already downloaded makes too many requests to CDA, and I can't download the second half. An option to skip parts of the folder or pause when there are too many requests would be useful.

**Comment by H4wk507** [comment]
Thanks for raising an issue! I will look into that later today.

**Comment by H4wk507** [comment]
@dam2452 #3 should solve your issue. Things that I've added: 
- Checking if the file is already downloaded makes 1 request instead of 2.
- Getting 429 error code (Too many requests) sleeps the current thread for 10 minutes.

Now you can run `pip install cda-dl -U` to get the latest version.
