### ISSUE TITLE
Wrong resolution

### ISSUE THREAD

**Issue by eryczkekamyczke** [H4wk507/cda-downloader#4]
When I try to download a movie it downloads to me in 480p resolution despite specifying 1080p. I tried download movie manualy, and 1080p has exist. 

https://prnt.sc/MxF-a8FKO02e

https://prnt.sc/WuaXMYOKYBwA

https://prnt.sc/vvGUvzMyMVh6

My manual download 
https://prnt.sc/Mm5nKxrukxqt

**Comment by H4wk507** [comment]
@eryczkekamyczke Thanks for raising an issue! I checked and indeed there was a bug where the specified resolution was ignored and the default resolution for a video would be used. I already fixed that in #5 and should be working now.
You can run `pip install cda-dl -U` to get the latest version of the program.
